#' Genomes available on gene-list.com
#'
#' The genomes \code{\link{gene_list}} can look identifiers up in, with the
#' common and scientific name of each species and the assembly the gene
#' annotations come from.
#'
#' Either name can be given as \code{genome}: \code{"rat"} and \code{"Rattus
#' norvegicus"} are the same genome. The \code{genome} column is the value the
#' site itself uses, which is a common name for some species and a scientific
#' one for others.
#'
#' @return A data frame with columns \code{genome}, \code{common_name},
#'   \code{scientific_name}, \code{assembly} and \code{group}, ordered as they
#'   appear in the species menu on the site: the commonly used model organisms
#'   first, then the rest by taxonomic group. \code{group} is that menu
#'   heading, so \code{subset(gene_list_genomes(), group == "Birds")} is the
#'   birds.
#'
#' @examples
#' gene_list_genomes()
#'
#' # Names that can be given to gene_list(genome = )
#' gene_list_genomes()[, c("common_name", "scientific_name")]
#'
#' @seealso \code{\link{gene_list_genome}} to resolve a name to the value the
#'   site expects.
#'
#' @export
gene_list_genomes <- function() {
  data.frame(
    genome = c(
      "human", "mouse", "rattus_norvegicus", "danio_rerio",
      "drosophila_melanogaster", "caenorhabditis_elegans", "yeast",
      "escherichia_coli", "arabidopsis_thaliana", "xenopus_tropicalis",
      "bos_taurus", "callithrix_jacchus", "canis_lupus_familiaris",
      "capra_hircus", "cavia_porcellus", "chlorocebus_sabaeus",
      "cricetulus_griseus_picr", "equus_caballus", "felis_catus",
      "heterocephalus_glaber_female", "macaca_fascicularis", "macaca_mulatta",
      "mesocricetus_auratus", "monodelphis_domestica",
      "mustela_putorius_furo", "myotis_lucifugus", "oryctolagus_cuniculus",
      "ovis_aries", "pan_troglodytes", "rhinolophus_ferrumequinum",
      "sus_scrofa", "anas_platyrhynchos", "columba_livia",
      "coturnix_japonica", "gallus_gallus", "meleagris_gallopavo",
      "melopsittacus_undulatus", "taeniopygia_guttata", "callorhinchus_milii",
      "gasterosteus_aculeatus", "latimeria_chalumnae", "lepisosteus_oculatus",
      "nothobranchius_furzeri", "oncorhynchus_mykiss",
      "oreochromis_niloticus", "oryzias_latipes", "petromyzon_marinus",
      "salmo_salar", "takifugu_rubripes", "ambystoma_mexicanum",
      "pleurodeles_waltl", "xenopus_laevis", "alligator_mississippiensis",
      "anolis_carolinensis", "chrysemys_picta", "naja_naja",
      "pogona_vitticeps", "trachemys_scripta", "aedes_aegypti",
      "aedes_albopictus", "anopheles_gambiae", "anopheles_stephensi",
      "apis_mellifera", "aplysia_californica", "bombyx_mori", "brugia_malayi",
      "caenorhabditis_briggsae", "ciona_intestinalis",
      "culex_quinquefasciatus", "daphnia_magna", "daphnia_pulex",
      "drosophila_simulans", "hydra_vulgaris", "hypsibius_exemplaris",
      "ixodes_scapularis", "nematostella_vectensis",
      "ramazzottius_varieornatus", "schistosoma_mansoni",
      "schmidtea_mediterranea", "strongylocentrotus_purpuratus",
      "tribolium_castaneum", "arabidopsis_lyrata", "brachypodium_distachyon",
      "brassica_napus", "brassica_oleracea", "brassica_rapa",
      "chlamydomonas_reinhardtii", "glycine_max", "gossypium_hirsutum",
      "hordeum_vulgare", "marchantia_polymorpha", "medicago_truncatula",
      "oryza_sativa", "physcomitrium_patens", "populus_trichocarpa",
      "setaria_italica", "setaria_viridis", "solanum_lycopersicum",
      "solanum_tuberosum", "sorghum_bicolor", "triticum_aestivum",
      "vitis_vinifera", "zea_mays", "aspergillus_fumigatus",
      "aspergillus_nidulans", "botrytis_cinerea", "candida_albicans",
      "candida_auris", "cryptococcus_neoformans", "komagataella_phaffii",
      "magnaporthe_oryzae", "neurospora_crassa", "schizosaccharomyces_pombe",
      "cryptosporidium_parvum", "dictyostelium_discoideum",
      "entamoeba_histolytica", "giardia_intestinalis", "leishmania_major",
      "plasmodium_falciparum", "plasmodium_vivax", "toxoplasma_gondii",
      "trichomonas_vaginalis", "trypanosoma_brucei",
      "acinetobacter_baumannii", "agrobacterium_fabrum", "bacillus_subtilis",
      "borrelia_burgdorferi", "campylobacter_jejuni", "chlamydia_trachomatis",
      "clostridioides_difficile", "enterococcus_faecium",
      "helicobacter_pylori", "klebsiella_pneumoniae",
      "legionella_pneumophila", "listeria_monocytogenes",
      "mycobacterium_tuberculosis", "neisseria_gonorrhoeae",
      "pseudomonas_aeruginosa", "salmonella_typhimurium",
      "staphylococcus_aureus", "streptococcus_pneumoniae",
      "streptococcus_pyogenes", "streptomyces_coelicolor",
      "synechocystis_6803", "vibrio_cholerae", "haloferax_volcanii",
      "methanocaldococcus_jannaschii", "pyrococcus_furiosus",
      "saccharolobus_solfataricus", "phage_lambda", "hepatitis_b",
      "herpes_simplex_1", "cytomegalovirus", "epstein_barr", "hiv_1",
      "papillomavirus_16", "respiratory_syncytial_virus", "influenza_a",
      "monkeypox", "sars_cov_2", "ebola_virus"
    ),
    common_name = c(
      "Human", "Mouse", "Rat", "Zebrafish", "Fruit fly", "Roundworm",
      "Baker's yeast", "E. coli", "Thale cress", "Tropical clawed frog",
      "Cattle", "Common marmoset", "Dog", "Goat", "Guinea pig",
      "African green monkey", "Chinese hamster (CHO)", "Horse", "Cat",
      "Naked mole-rat", "Cynomolgus macaque", "Rhesus macaque",
      "Golden hamster", "Grey short-tailed opossum", "Ferret",
      "Little brown bat", "Rabbit", "Sheep", "Chimpanzee",
      "Greater horseshoe bat", "Pig", "Mallard duck", "Rock pigeon",
      "Japanese quail", "Chicken", "Turkey", "Budgerigar", "Zebra finch",
      "Elephant shark", "Three-spined stickleback", "Coelacanth",
      "Spotted gar", "Turquoise killifish", "Rainbow trout", "Nile tilapia",
      "Medaka", "Sea lamprey", "Atlantic salmon", "Fugu", "Axolotl",
      "Iberian ribbed newt", "African clawed frog", "American alligator",
      "Green anole", "Painted turtle", "Indian cobra",
      "Central bearded dragon", "Red-eared slider", "Yellow fever mosquito",
      "Asian tiger mosquito", "Malaria mosquito", "Asian malaria mosquito",
      "Honey bee", "California sea hare", "Silkworm", "Filarial worm",
      "Nematode (briggsae)", "Sea vase", "Southern house mosquito",
      "Water flea", "Common water flea", "Fruit fly (simulans)", "Hydra",
      "Water bear", "Black-legged tick", "Starlet sea anemone",
      "Water bear (Ramazzottius)", "Blood fluke", "Planarian",
      "Purple sea urchin", "Red flour beetle", "Lyrate rockcress",
      "Purple false brome", "Canola", "Cabbage", "Field mustard",
      "Green alga", "Soybean", "Cotton", "Barley", "Common liverwort",
      "Barrel medic", "Rice", "Spreading earthmoss", "Black cottonwood",
      "Foxtail millet", "Green foxtail", "Tomato", "Potato", "Sorghum",
      "Bread wheat", "Grape", "Maize", "A. fumigatus", "A. nidulans",
      "Grey mould", "C. albicans", "C. auris", "C. neoformans",
      "Pichia pastoris", "Rice blast fungus", "Red bread mould",
      "Fission yeast", "Cryptosporidium", "Slime mould", "Entamoeba",
      "Giardia", "Leishmania", "Malaria parasite", "Malaria parasite (vivax)",
      "Toxoplasma", "Trichomonas", "Sleeping sickness parasite",
      "A. baumannii", "Agrobacterium", "B. subtilis",
      "Lyme disease bacterium", "Campylobacter", "Chlamydia", "C. difficile",
      "E. faecium", "H. pylori", "K. pneumoniae", "Legionella", "Listeria",
      "M. tuberculosis", "N. gonorrhoeae", "P. aeruginosa", "Salmonella",
      "S. aureus", "S. pneumoniae", "Group A strep", "S. coelicolor",
      "Synechocystis", "Cholera bacterium", "Haloferax", "Methanocaldococcus",
      "Pyrococcus", "Sulfolobus", "Phage lambda", "Hepatitis B",
      "Herpes simplex 1", "Cytomegalovirus", "Epstein-Barr virus", "HIV-1",
      "HPV-16", "RSV", "Influenza A", "Mpox", "SARS-CoV-2", "Ebola virus"
    ),
    scientific_name = c(
      "Homo sapiens", "Mus musculus", "Rattus norvegicus", "Danio rerio",
      "Drosophila melanogaster", "Caenorhabditis elegans",
      "Saccharomyces cerevisiae", "Escherichia coli K-12",
      "Arabidopsis thaliana", "Xenopus tropicalis", "Bos taurus",
      "Callithrix jacchus", "Canis lupus familiaris", "Capra hircus",
      "Cavia porcellus", "Chlorocebus sabaeus", "Cricetulus griseus",
      "Equus caballus", "Felis catus", "Heterocephalus glaber",
      "Macaca fascicularis", "Macaca mulatta", "Mesocricetus auratus",
      "Monodelphis domestica", "Mustela putorius furo", "Myotis lucifugus",
      "Oryctolagus cuniculus", "Ovis aries", "Pan troglodytes",
      "Rhinolophus ferrumequinum", "Sus scrofa", "Anas platyrhynchos",
      "Columba livia", "Coturnix japonica", "Gallus gallus",
      "Meleagris gallopavo", "Melopsittacus undulatus", "Taeniopygia guttata",
      "Callorhinchus milii", "Gasterosteus aculeatus", "Latimeria chalumnae",
      "Lepisosteus oculatus", "Nothobranchius furzeri", "Oncorhynchus mykiss",
      "Oreochromis niloticus", "Oryzias latipes", "Petromyzon marinus",
      "Salmo salar", "Takifugu rubripes", "Ambystoma mexicanum",
      "Pleurodeles waltl", "Xenopus laevis", "Alligator mississippiensis",
      "Anolis carolinensis", "Chrysemys picta bellii", "Naja naja",
      "Pogona vitticeps", "Trachemys scripta elegans", "Aedes aegypti",
      "Aedes albopictus", "Anopheles gambiae", "Anopheles stephensi",
      "Apis mellifera", "Aplysia californica", "Bombyx mori", "Brugia malayi",
      "Caenorhabditis briggsae", "Ciona intestinalis",
      "Culex quinquefasciatus", "Daphnia magna", "Daphnia pulex",
      "Drosophila simulans", "Hydra vulgaris", "Hypsibius exemplaris",
      "Ixodes scapularis", "Nematostella vectensis",
      "Ramazzottius varieornatus", "Schistosoma mansoni",
      "Schmidtea mediterranea", "Strongylocentrotus purpuratus",
      "Tribolium castaneum", "Arabidopsis lyrata", "Brachypodium distachyon",
      "Brassica napus", "Brassica oleracea", "Brassica rapa",
      "Chlamydomonas reinhardtii", "Glycine max", "Gossypium hirsutum",
      "Hordeum vulgare", "Marchantia polymorpha", "Medicago truncatula",
      "Oryza sativa", "Physcomitrium patens", "Populus trichocarpa",
      "Setaria italica", "Setaria viridis", "Solanum lycopersicum",
      "Solanum tuberosum", "Sorghum bicolor", "Triticum aestivum",
      "Vitis vinifera", "Zea mays", "Aspergillus fumigatus Af293",
      "Aspergillus nidulans", "Botrytis cinerea", "Candida albicans SC5314",
      "Candidozyma auris", "Cryptococcus neoformans H99",
      "Komagataella phaffii", "Magnaporthe oryzae", "Neurospora crassa",
      "Schizosaccharomyces pombe", "Cryptosporidium parvum",
      "Dictyostelium discoideum", "Entamoeba histolytica",
      "Giardia intestinalis", "Leishmania major Friedlin",
      "Plasmodium falciparum", "Plasmodium vivax", "Toxoplasma gondii ME49",
      "Trichomonas vaginalis", "Trypanosoma brucei",
      "Acinetobacter baumannii ATCC 17978", "Agrobacterium fabrum",
      "Bacillus subtilis 168", "Borreliella burgdorferi",
      "Campylobacter jejuni", "Chlamydia trachomatis",
      "Clostridioides difficile 630", "Enterococcus faecium Aus0004",
      "Helicobacter pylori 26695", "Klebsiella pneumoniae HS11286",
      "Legionella pneumophila", "Listeria monocytogenes",
      "Mycobacterium tuberculosis H37Rv", "Neisseria gonorrhoeae FA 1090",
      "Pseudomonas aeruginosa PAO1", "Salmonella Typhimurium LT2",
      "Staphylococcus aureus NCTC 8325", "Streptococcus pneumoniae TIGR4",
      "Streptococcus pyogenes", "Streptomyces coelicolor A3(2)",
      "Synechocystis sp. PCC 6803", "Vibrio cholerae", "Haloferax volcanii",
      "Methanocaldococcus jannaschii", "Pyrococcus furiosus",
      "Saccharolobus solfataricus", "Escherichia phage lambda",
      "Hepatitis B virus", "Human alphaherpesvirus 1",
      "Human betaherpesvirus 5", "Human gammaherpesvirus 4",
      "Human immunodeficiency virus 1", "Human papillomavirus 16",
      "Human respiratory syncytial virus", "Influenza A virus",
      "Monkeypox virus", "Severe acute respiratory syndrome coronavirus 2",
      "Zaire ebolavirus"
    ),
    assembly = c(
      "GRCh38", "GRCm39", "GRCr8", "GRCz11", "BDGP6", "WBcel235", "R64-1-1",
      "ASM584v2", "TAIR10", "UCB_Xtro_10.0", "ARS-UCD2.0", "mCalJac1.pat.X",
      "ROS_Cfam_1.0", "ARS1", "Cavpor3.0", "ChlSab1.1", "CriGri-PICRH-1.0",
      "EquCab3.0", "Fca126_mat1.0", "Naked_mole-rat_maternal",
      "Macaca_fascicularis_6.0", "Mmul_10", "MesAur1.0", "ASM229v1",
      "MusPutFur1.0", "Myoluc2.0", "OryCun2.0", "ARS-UI_Ramb_v3.0",
      "Pan_tro_3.0", "mRhiFer1_v1.p", "Sscrofa11.1", "ASM874695v1",
      "bColLiv1.pat.W.v2", "Coturnix_japonica_2.0", "GRCg7b", "Turkey_5.1",
      "bMelUnd1.mat.Z", "bTaeGut1_v1.p", "Callorhinchus_milii-6.1.3",
      "GAculeatus_UGA_version5", "LatCha1", "LepOcu1", "Nfu_20140520",
      "USDA_OmykA_1.1", "UMD_NMBU", "ASM223467v1", "Pmarinus_7.0",
      "Ssal_v3.1", "fTakRub1.2", "UKY_AmexF1_1", "aPleWal1.hap1",
      "Xenopus_laevis_v10.1", "rAllMis1", "AnoCar2.0v2",
      "Chrysemys_picta_bellii-3.0.3", "Nana_v5", "PviZW2.1", "CAS_Tse_1.0",
      "AaegL5", "GCA035046485v1", "AgamP4", "AsteI2", "Amel_HAv3.1",
      "AplCal3.0", "ASM3026992v2", "Bmal-4.0", "CB4", "ASM1832782v2",
      "VPISU_Cqui_1.0", "ASM2063170v1.1", "ASM2113471v1", "Prin_Dsim_3.1",
      "HydraT2T_AEP", "nHd_3.1", "ASM1692078v2", "jaNemVect1.1", "Rvar_4.0",
      "Smansoni_v7", "schMedS3h2", "Spur_5.0", "icTriCast1.1", "v.1.0",
      "v3.0", "AST_PRJEB5043_v1", "BOL", "Brapa_1.0", "v5.5",
      "Glycine_max_v2.1", "TM-1 v2.1", "MorexV3", "MpTak1_v7.1",
      "MtrunA17r5.0", "IRGSP-1.0", "Phypa V3", "Pop_tri_v4", "v2.0", "v2.0",
      "SL4.0", "SolTub_3.0", "NCBIv3", "IWGSC", "ASM3070453v1", "B73 NAM-5.0",
      "GCA000002655v1", "ASM1142v1", "ASM83294v1", "Assembly 22",
      "GCA002759435v2", "CNA3", "ASM2700v1", "GCA900474545v2", "NC12",
      "ASM294v2", "ASM16534v1", "dicty_2.7", "JCVI-ESG2-1.0",
      "GCA000002435v2", "ASM272v2", "GCA000002765v3", "GCA900093555v2",
      "TGA4", "ASM282v3", "GCA000002445v1", "ASM1542v1", "ASM9202v1",
      "ASM904v1", "ASM868v2", "ASM908v1", "ASM872v1", "ASM920v2",
      "ASM25094v2", "ASM852v1", "ASM24018v2", "ASM848v1", "ASM19603v1",
      "ASM19595v2", "ASM684v1", "ASM676v1", "ASM694v2", "ASM1342v1",
      "ASM688v1", "ASM678v2", "ASM20383v1", "ASM972v1", "ASM674v1",
      "ASM2568v1", "ASM9166v1", "ASM730v1", "ASM700v1", "ViralProj14204",
      "ViralProj15428", "strain 17", "Merlin", "ASM240226v1", "HXB2",
      "ViralProj15505", "ASM281547v1", "A/PR/8/1934 (H1N1)", "Zaire-96-I-16",
      "ASM985889v3", "Mayinga 1976"
    ),
    group = c(
      "Commonly used", "Commonly used", "Commonly used", "Commonly used",
      "Commonly used", "Commonly used", "Commonly used", "Commonly used",
      "Commonly used", "Commonly used", "Mammals", "Mammals", "Mammals",
      "Mammals", "Mammals", "Mammals", "Mammals", "Mammals", "Mammals",
      "Mammals", "Mammals", "Mammals", "Mammals", "Mammals", "Mammals",
      "Mammals", "Mammals", "Mammals", "Mammals", "Mammals", "Mammals",
      "Birds", "Birds", "Birds", "Birds", "Birds", "Birds", "Birds", "Fish",
      "Fish", "Fish", "Fish", "Fish", "Fish", "Fish", "Fish", "Fish", "Fish",
      "Fish", "Amphibians", "Amphibians", "Amphibians", "Reptiles",
      "Reptiles", "Reptiles", "Reptiles", "Reptiles", "Reptiles",
      "Invertebrates", "Invertebrates", "Invertebrates", "Invertebrates",
      "Invertebrates", "Invertebrates", "Invertebrates", "Invertebrates",
      "Invertebrates", "Invertebrates", "Invertebrates", "Invertebrates",
      "Invertebrates", "Invertebrates", "Invertebrates", "Invertebrates",
      "Invertebrates", "Invertebrates", "Invertebrates", "Invertebrates",
      "Invertebrates", "Invertebrates", "Invertebrates", "Plants", "Plants",
      "Plants", "Plants", "Plants", "Plants", "Plants", "Plants", "Plants",
      "Plants", "Plants", "Plants", "Plants", "Plants", "Plants", "Plants",
      "Plants", "Plants", "Plants", "Plants", "Plants", "Plants", "Fungi",
      "Fungi", "Fungi", "Fungi", "Fungi", "Fungi", "Fungi", "Fungi", "Fungi",
      "Fungi", "Protists", "Protists", "Protists", "Protists", "Protists",
      "Protists", "Protists", "Protists", "Protists", "Protists", "Bacteria",
      "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria",
      "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria",
      "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria", "Bacteria",
      "Bacteria", "Bacteria", "Bacteria", "Archaea", "Archaea", "Archaea",
      "Archaea", "Viruses", "Viruses", "Viruses", "Viruses", "Viruses",
      "Viruses", "Viruses", "Viruses", "Viruses", "Viruses", "Viruses",
      "Viruses"
    ),
    stringsAsFactors = FALSE
  )
}
